[ID-184]Consolidate the information, and make it accessible with a single API call (#186)
* set the Changelog.md

* set the model and the docs

* fix the docs

* fix the docs and web part start of the api

* fix the docs

* structure the API

* get user response

* get message recipient and messages with userID

* set find queue data

* make it async

* fix lint issues

* remove unused code and fix the UserDataResponse model

* fix the response json

* in progress

* in progress

* fix the API

* fix   Module: golang.org/x/net
    Found in: golang.org/x/net@v0.25.0
    Fixed in: golang.org/x/net@v0.33.0
    Example traces found:
Error:       #1: utils/utils.go:68:43: utils.ModifyHTMLContent calls goquery.NewDocumentFromReader, which calls html.Parse
Error:       #2: utils/utils.go:89:27: utils.ModifyHTMLContent calls goquery.Selection.ReplaceWithHtml, which eventually calls html.ParseFragment

* in progress

* make the function async

* fix docs and in progress

* fix the API

---------

Co-authored-by: Stefan Vitanov <stefan@inabyte.com>